## Crear entorno de Python


Descargar Python: 
https://www.python.org/

Dirigirse al área/Dirección de trabajo  

Crer Entorno: python -m venv Nombre_Entorno


Ejecutar entorno en terminal: 
- En Windows, ejecuta: Nombre_Entorno\Scripts\activate
- En Unix o MacOS, ejecuta: source Nombre_Entorno/bin/activate

Para salir utiliza el comando deativate

----------------------------------------------------------------------------------------------------



Listas de listas distinto a matriz 

In [ ]:
a = [[12,3,8],[89,2,5],[7,8,6]]
b = [[12,3,8],[89,2,5],[7,8,6]]
print (a+b)

[[12, 3, 8], [89, 2, 5], [7, 8, 6], [12, 3, 8], [89, 2, 5], [7, 8, 6]]


Se utiliza numpy para convertir 

In [1]:

import numpy as np
a = np.array([[12,3,8],[89,2,5],[7,8,6]])
b = np.array([[12,3,8],[89,2,5],[7,8,6]])
print (a+b)

[[ 24   6  16]
 [178   4  10]
 [ 14  16  12]]


Ahora se trabbajara como un string*

*numpy puede  tambien aplicar para caracteres*

In [1]:
a = np.array(['hola','mundo'])
b = np.array(['padiuxhi', 'guidxiyu'])
c = np.array([1,2,5,6])
print(a+b)

NameError: name 'np' is not defined

Dimensiones consistebtes 

In [ ]:
a = np.array([[2,5,1],[3,10,12],[2,0,0]])
b = np.array()

Operaciones matriciales: 
    - Producto interno 
    - Conocer dimensiones
    - 



In [ ]:
print(np.dot(b,a)) #Producto de matrices
print(a.shape)