## Crear entorno de Python


Descargar Python: 
https://www.python.org/

Dirigirse al área/Dirección de trabajo  

Crer Entorno: python -m venv Nombre_Entorno


Ejecutar entorno en terminal: 
- En Windows, ejecuta: Nombre_Entorno\Scripts\activate
- En Unix o MacOS, ejecuta: source Nombre_Entorno/bin/activate

Para salir utiliza el comando deativate

----------------------------------------------------------------------------------------------------



## Importar librerias 

In [37]:
import numpy as np
import pandas as pd

Asignación de variables

In [ ]:
# Númericas
var1 = 10
var2 = 10.10 
var3 = "10"
var4 = True
#####################
print(var1, var2, var3)

print(type(var1), type(var2), type(var3), type(var4))

# Bucles, condicionales y funciones 

In [41]:
## FOR 
## for variable i,j,k in range(inicio, alto, paso): 
## Hace algo 

for i in range(1,100, 1):
    n = i + 1
    print(n) 

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
## Ejercicio retomado de cisco - skills for all, curso de fundamentos de python I
# Un programa que lee una secuencia de números
# y cuenta cuántos números son pares y cuántos son impares.
# El programa termina cuando se ingresa un cero.

## Impares
odd_numbers = 0
## pARE
even_numbers = 0

# Lee el primer número.
number = int(input("Introduce un número o escribe 0 para detener: "))

# 0 termina la ejecución.
while number != 0:
    # Verificar si el número es impar.
    if number % 2 == 1:
        # Incrementar el contador de números impares odd_numbers.
        odd_numbers += 1
    else:
        # Incrementar el contador de números pares even_numbers.
        even_numbers += 1
    # Leer el siguiente número.
    number = int(input("Introduce un número o escribe 0 para detener: "))

# Imprimir resultados.
print("Conteo de números impares:", odd_numbers)
print("Conteo de números pares:", even_numbers)



## Funciones

In [2]:

# def NombreFuncion(Variables +1): 
# Funciones que va a realizar la funcion
# return Valor que puede o no retornar


# Sin utilizar return
def message(): 
    print("Hola, ¿me llamaste?")
# Utilizando return 
def message(): 
    return print("Hola, ¿me llamaste?")


In [ ]:
def contador(x): 
    for i in range(x):
        n = i + 1
        print(n)
    return x 
        
x = 10
contador(x)

In [ ]:
# You are given an integer array prices where prices[i] is the price of a given stock on the ith day.
# On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. 
# However, you can buy it then immediately sell it on the same day. 
# Find and return the maximum profit you can achieve.


### Inicializamos la función con def nombre_funcion(variables)
def maxProfit(prices):  
    # Inicializamos nuestras ganancias en 0 
    profit = 0
    # Inicializamos el ciclo for, este va a ir en un rango de i = 1 hasta el tamaño de la variable solicitada i = len(prices)
    for i in range(1, len(prices)): 
        # Condicionale para identificar si la posición actual es mayor a la anterior
        if (prices[i] > prices[i -1]):
            # Se hace la venta en el caso de que sea el mayor 
            # el operador += indica incremento 
            # otra forma de escribirlo es profit = profit + (prices[i] - prices[i-1])   
            profit += (prices[i] - prices[i-1])
    # Return indica si va a devolver o no una variable
    # En este caso devuelve las variable de ganancias/profit        
    return profit
prices = [7,5,4,3,2,1,10]
maxProfit(prices)


## Matrices y vectores

In [38]:
Vector = np.array(["Hola","amigos","de micro"])
Matriz = np.array([[1,2,3],[5,6,7],[8,9,10]])
tensor = np.array([[[1,2,3],[5,6,7],[8,9,10]],[[1,2,3],[5,6,7],[8,9,10]], [[1,2,3],[5,6,7],[8,9,10]]]) 
print(Vector, "\n")
print("-----------------------------------")
print(Matriz, "\n")
print("-----------------------------------")
print(tensor)

['Hola' 'amigos' 'de micro'] 

-----------------------------------
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]] 

-----------------------------------
[[[ 1  2  3]
  [ 5  6  7]
  [ 8  9 10]]

 [[ 1  2  3]
  [ 5  6  7]
  [ 8  9 10]]

 [[ 1  2  3]
  [ 5  6  7]
  [ 8  9 10]]]


In [39]:
vacio = [[]]
a = [[12,3,8],[89,2,5],[7,8,6]]
b = [[12,3,8],[89,2,5],[7,8,6]]
print (a+b, vacio)

[[12, 3, 8], [89, 2, 5], [7, 8, 6], [12, 3, 8], [89, 2, 5], [7, 8, 6]] [[]]


In [ ]:

a = np.array([[12,3,8],[89,2,5],[7,8,6]])
b = np.array([[12,3,8],[89,2,5],[7,8,6]])
print (a+b)

### Atributos de un array 
- ndim
- shape
- size 
- dtype

In [ ]:
## ndim 

print(Vector.ndim)
print(Matriz.ndim)
print(tensor.ndim)

In [ ]:
# shape

print(Vector.shape)
print(Matriz.shape)
print(tensor.shape)

In [ ]:
# Size 
print(Vector.size)
print(Matriz.size)
print(tensor.size)

In [ ]:
# dtype 

print(Vector.dtype)
print(Matriz.dtype)
print(tensor.dtype)

Operaciones matriciales: 
    - Producto interno 
    - Conocer dimensiones
    

In [ ]:
a = np.array(['hola','mundo'])
b = np.array(['padiuxhi', 'guidxiyu'])
print(a+b)
# print(a+c)

Operaciones matriciales: 
    - Producto interno 
    - Conocer dimensiones
    - 



In [ ]:
print(np.dot(b,a)) #Producto de matrices