## Crear entorno de Python


Descargar Python: 
https://www.python.org/

Dirigirse al área/Dirección de trabajo  

Crer Entorno: python -m venv Nombre_Entorno


Ejecutar entorno en terminal: 
- En Windows, ejecuta: Nombre_Entorno\Scripts\activate
- En Unix o MacOS, ejecuta: source Nombre_Entorno/bin/activate

Para salir utiliza el comando deativate

----------------------------------------------------------------------------------------------------



## Importar librerias 

In [15]:
import numpy as np
import pandas as pd


Asignación de variables

In [ ]:
## Numericas
var1 = 10
var2 = 10.10 
## Caracter 
var3 = "10"
# Booleanas
var4 = True
#####################

vector =  [1,2,3,4,5,6]
matriz = [[1,2,3],[4,5,6],[7,8,9]]
print( var1, "\n", var2 , "\n", var3, "\n", vector, "\n", matriz)

print(type(var1), type(var2), type(var3), type(var4), type(vector), type(matriz))

### Operaciones Basicas

In [ ]:
sum = var1 + var2
mult = var2 * 5 
div = var1 / var2 
concatenar = var3 + var3
exp = var1 ** 2
suma_Booleana = True + False

print(sum, "\n", mult, "\n", div, "\n", concatenar, "\n", exp, "\n", suma_Booleana)

# Bucles, condicionales y funciones 

In [ ]:
## FOR 
## for variable i,j,k in range(inicio, alto, paso): 
## Hace algo 

if (var1 == 10):
    print("el valor es 10")

for i in range(1,100, 1):
    n = i + 1
    print(n) 

In [ ]:
## Ejercicio retomado de cisco - skills for all, curso de fundamentos de python I
# Un programa que lee una secuencia de números
# y cuenta cuántos números son pares y cuántos son impares.
# El programa termina cuando se ingresa un cero.

## Impares
odd_numbers = 0
## pARE
even_numbers = 0

# Lee el primer número.
number = int(input("Introduce un número o escribe 0 para detener: "))

# 0 termina la ejecución.
while number != 0:
    # Verificar si el número es impar.
    if number % 2 == 1:
        # Incrementar el contador de números impares odd_numbers.
        odd_numbers += 1
    else:
        # Incrementar el contador de números pares even_numbers.
        even_numbers += 1
    # Leer el siguiente número.
    number = int(input("Introduce un número o escribe 0 para detener: "))

# Imprimir resultados.
print("Conteo de números impares:", odd_numbers)
print("Conteo de números pares:", even_numbers)



## Funciones

In [10]:

# def NombreFuncion(Variables +1): 
# Funciones que va a realizar la funcion
# return Valor que puede o no retornar


# Sin utilizar return
def message(): 
    print("Hola, ¿me llamaste?")
# Utilizando return 
def message(): 
    return print("Hola, ¿me llamaste?")


In [ ]:


message()

In [ ]:
def contador(x): 
    for i in range(x):
        n = i + 1
        print(n)
    return x 
        
x = 10
contador(x)

In [ ]:
# You are given an integer array prices where prices[i] is the price of a given stock on the ith day.
# On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. 
# However, you can buy it then immediately sell it on the same day. 
# Find and return the maximum profit you can achieve.


### Inicializamos la función con def nombre_funcion(variables)
def maxProfit(prices):  
    # Inicializamos nuestras ganancias en 0 
    profit = 0
    # Inicializamos el ciclo for, este va a ir en un rango de i = 1 hasta el tamaño de la variable solicitada i = len(prices)
    for i in range(1, len(prices)): 
        # Condicionale para identificar si la posición actual es mayor a la anterior
        if (prices[i] > prices[i -1]):
            # Se hace la venta en el caso de que sea el mayor 
            # el operador += indica incremento 
            # otra forma de escribirlo es profit = profit + (prices[i] - prices[i-1])   
            profit += (prices[i] - prices[i-1])
    # Return indica si va a devolver o no una variable
    # En este caso devuelve las variable de ganancias/profit        
    return profit
prices = [7,5,4,3,2,1,10]
maxProfit(prices)


## Matrices y vectores

In [ ]:
Vector = np.array(["Hola","amigos","de micro"])
Matriz = np.array([[1,2,3],[5,6,7],[8,9,10]])
tensor = np.array([[[1,2,3],[5,6,7],[8,9,10]],[[1,2,3],[5,6,7],[8,9,10]], [[1,2,3],[5,6,7],[8,9,10]]]) 
print(Vector, "\n")
print("-----------------------------------")
print(Matriz, "\n")
print("-----------------------------------")
print(tensor)

### Operaciones con Numpy

In [62]:
# Crear un vector con valores "aleatorios"
vector = np.random.randint(1, 1000, (4))
vector
# Matrices aleatorias 
matriz = np.random.randint(1, 1000, (4,4))
matriz

array([[514, 744, 362, 761],
       [654, 727, 949,  23],
       [ 95, 861, 600, 351],
       [310, 334, 665, 848]], dtype=int32)

In [79]:
vector1 = np.random.randint(1, 20, (4))
print(vector1, "\n")
vector2 = np.random.randint(1, 20, (4))
print(vector2, "\n")

print("suma =", vector1 + vector2, "\n")
print("resta  =", vector1 - vector2, "\n")
print("mult =", vector1 * vector2, "\n")
print("exp =", vector1 ** vector2, "\n")
print("promedio =",np.mean(vector1), "\n")
print("var =", np.var(vector1), "\n")
print("mediana =", np.median(vector1), "\n")




[ 5 11 17  5] 

[10 17 13 12] 

suma = [15 28 30 17] 

resta  = [-5 -6  4 -7] 

mult = [ 50 187 221  60] 

exp = [   9765625  -92658101 1196240593  244140625] 

promedio = 9.5 

var = 24.75 

mediana = 8.0 



In [97]:

matriz1 = np.random.randint(1, 20, (4,4))
print(matriz1, "\n")
matriz2 = np.random.randint(1, 20, (4,4))
print(matriz2, "\n") 

print("suma =", vector1 + vector2, "\n")
print("resta  =", vector1 - vector2, "\n")
print("mult =", vector1 * vector2, "\n")
print("exp =", vector1 ** vector2, "\n")
print("promedio =",np.mean(vector1), "\n")
print("var =", np.var(vector1), "\n")
print("mediana =", np.median(vector1), "\n")



#print("----------------------")
#seleccion de filas
#print(matriz1[:,0], "\n")
# Seleccion de columnas
#print(matriz1[0,:], "\n")


[[12 11  8  5]
 [17 16  2  5]
 [12  4  4 11]
 [ 4 17  2 10]] 

[[12  6 16  3]
 [ 8  4  9  3]
 [ 3  9 19  3]
 [ 3 14 17 11]] 

suma = [15 28 30 17] 

resta  = [-5 -6  4 -7] 

mult = [ 50 187 221  60] 

exp = [   9765625  -92658101 1196240593  244140625] 

promedio = 9.5 

var = 24.75 

mediana = 8.0 



'\nprint("----------------------")\n#seleccion de filas\nprint(matriz1[:,0], "\n")\n# Seleccion de columnas\nprint(matriz1[0,:], "\n")\n'

In [ ]:
vacio = [[],[],[]]
a = [[12,3,8],[89,2,5],[7,8,6]]
b = [[12,3,8],[89,2,5],[7,8,6]]
print (a + b)

In [ ]:

a = np.array([[12,3,8],[89,2,5],[7,8,6]])
b = np.array([[12,3,8],[89,2,5],[7,8,6]])
print (a + b)

### Atributos de un array 
- ndim
- shape
- size 
- dtype

In [ ]:
## ndim 

print(Vector.ndim)
print(Matriz.ndim)
print(tensor.ndim)

In [ ]:
# shape

print(Vector.shape)
print(Matriz.shape)
print(tensor.shape)

In [ ]:
# Size 
print(Vector.size)
print(Matriz.size)
print(tensor.size)

In [ ]:
# dtype 

print(Vector.dtype)
print(Matriz.dtype)
print(tensor.dtype)

In [ ]:
## Concatenacion de matrices 
a = np.array(['hola','mundo'])
b = np.array(['padiuxhi', 'guidxiyu'])
print(a+b)
# print(a+c)

In [ ]:
print(np.dot(b,a)) #Producto de matrices