## Crear entorno de Python


Descargar Python: 
https://www.python.org/

Dirigirse al área/Dirección de trabajo  

Crer Entorno: python -m venv Nombre_Entorno


Ejecutar entorno en terminal: 
- En Windows, ejecuta: Nombre_Entorno\Scripts\activate
- En Unix o MacOS, ejecuta: source Nombre_Entorno/bin/activate

Para salir utiliza el comando deativate

----------------------------------------------------------------------------------------------------



## Importar librerias 

In [2]:
import numpy as np


Asignación de variables

In [3]:
# Númericas
var1 = 10
var2 = 10.10 
var3 = "10"
var4 = True
#####################
print(var1, var2, var3)

print(type(var1), type(var2), type(var3), type(var4))

10 10.1 10
<class 'int'> <class 'float'> <class 'str'> <class 'bool'>


# Bucles, condicionales y funciones 

In [69]:
## Ejercicio retomado de cisco - skills for all, curso de fundamentos de python I
# Un programa que lee una secuencia de números
# y cuenta cuántos números son pares y cuántos son impares.
# El programa termina cuando se ingresa un cero.

## Impares
odd_numbers = 0
## pARE
even_numbers = 0

# Lee el primer número.
number = int(input("Introduce un número o escribe 0 para detener: "))

# 0 termina la ejecución.
while number != 0:
    # Verificar si el número es impar.
    if number % 2 == 1:
        # Incrementar el contador de números impares odd_numbers.
        odd_numbers += 1
    else:
        # Incrementar el contador de números pares even_numbers.
        even_numbers += 1
    # Leer el siguiente número.
    number = int(input("Introduce un número o escribe 0 para detener: "))

# Imprimir resultados.
print("Conteo de números impares:", odd_numbers)
print("Conteo de números pares:", even_numbers)



Conteo de números impares: 4
Conteo de números pares: 1


In [30]:
# You are given an integer array prices where prices[i] is the price of a given stock on the ith day.
# On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. 
# However, you can buy it then immediately sell it on the same day. 
# Find and return the maximum profit you can achieve.


### Inicializamos la función con def nombre_funcion(variables)
def maxProfit(prices):  
    # Inicializamos nuestras ganancias en 0 
    profit = 0
    # Inicializamos el ciclo for, este va a ir en un rango de i = 1 hasta el tamaño de la variable solicitada i = len(prices)
    for i in range(1, len(prices)): 
        # Condicionale para identificar si la posición actual es mayor a la anterior
        if (prices[i] > prices[i -1]):
            # Se hace la venta en el caso de que sea el mayor 
            # el operador += indica incremento 
            # otra forma de escribirlo es profit = profit + (prices[i] - prices[i-1])   
            profit += (prices[i] - prices[i-1])
    # Return indica si va a devolver o no una variable
    # En este caso devuelve las variable de ganancias/profit        
    return profit
prices = [7,5,4,3,2,1,10]
maxProfit(prices)


1
2
3
4
5
6
7
8
9
1 

1
2
3
4
5
6
7
8
9
2 

1
2
3
4
5
6
7
8
9
3 

1
2
3
4
5
6
7
8
9
4 

1
2
3
4
5
6
7
8
9
5 

1
2
3
4
5
6
7
8
9
6 

1
2
3
4
5
6
7
8
9
7 

1
2
3
4
5
6
7
8
9
8 

1
2
3
4
5
6
7
8
9
9 



## Matrices y vectores

In [ ]:
Vector = np.array(["Hola","amigos","de micro"])
Matriz = np.array([[1,2,3],[5,6,7],[8,9,10]])
tensor = np.array([[[1,2,3],[5,6,7],[8,9,10]],[[1,2,3],[5,6,7],[8,9,10]], [[1,2,3],[5,6,7],[8,9,10]]]) 
print(Vector, "\n")
print("-----------------------------------")
print(Matriz, "\n")
print("-----------------------------------")
print(tensor)

In [65]:
vacio = [[]]
a = [[12,3,8],[89,2,5],[7,8,6]]
b = [[12,3,8],[89,2,5],[7,8,6]]
print (a+b, vacio)

[[12, 3, 8], [89, 2, 5], [7, 8, 6], [12, 3, 8], [89, 2, 5], [7, 8, 6]] [[]]


In [3]:

a = np.array([[12,3,8],[89,2,5],[7,8,6]])
b = np.array([[12,3,8],[89,2,5],[7,8,6]])
print (a+b)

[[ 24   6  16]
 [178   4  10]
 [ 14  16  12]]


### Atributos de un array 
- ndim
- shape
- size 
- dtype

In [47]:
## ndim 

print(Vector.ndim)
print(Matriz.ndim)
print(tensor.ndim)

1
2
3


In [48]:
# shape

print(Vector.shape)
print(Matriz.shape)
print(tensor.shape)

(3,)
(3, 3)
(3, 3, 3)


In [49]:
# Size 
print(Vector.size)
print(Matriz.size)
print(tensor.size)

3
9
27


In [50]:
# dtype 

print(Vector.dtype)
print(Matriz.dtype)
print(tensor.dtype)

<U8
int64
int64


Operaciones matriciales: 
    - Producto interno 
    - Conocer dimensiones
    

In [20]:
a = np.array(['hola','mundo'])
b = np.array(['padiuxhi', 'guidxiyu'])
print(a+b)
# print(a+c)

['holapadiuxhi' 'mundoguidxiyu']


Operaciones matriciales: 
    - Producto interno 
    - Conocer dimensiones
    - 



In [68]:
print(np.dot(b,a)) #Producto de matrices

[[ 25  60  62]
 [182 520 604]
 [ 14  10   2]]
